platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

def shared_pods
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxDataSources', '~> 3.0'
end

target 'GoodMeals' do
  shared_pods
end

target 'GoodMealsTests' do
  shared_pods
end

target 'GoodMealsUITests' do
  shared_pods
end
