platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

def shared_pods
  pod 'RxSwift', '~> 4.4'
  pod 'RxCocoa', '~> 4.4'
  pod 'RxDataSources', '~> 3.1'
  pod 'RealmSwift', '~> 3.14'
  pod 'SDWebImage', '~> 5.0'
end

target 'GoodMeals' do
  shared_pods
end

target 'GoodMealsTests' do
  shared_pods
  
  # Pods for testing
  pod 'RxBlocking', '= 4.4.2'
  pod 'RxTest', '= 4.4.2'
end
